@@ -7,7 +7,7 @@ on:



  workflow_dispatch:







env:



  GHCR_REPO: ghcr.io/aurora-develop/aurora



  GHCR_REPO: ghcr.io/dingli8888/chatapi







jobs:

main:

@@ -48,4 +48,4 @@ jobs:

${{ env.GHCR_REPO }}:latest



            ${{ env.GHCR_REPO }}:${{ github.sha }}



          cache-from: type=local,src=/tmp/.buildx-cache



          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max



          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
